spring:
  main:
    banner-mode: "OFF"
  datasource:
    url: jdbc:h2:file:~/demo
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

filename: "input.txt.gz"

logging:
  level:
    root: INFO

server:
  shutdown: graceful